import type { Metadata } from 'next'
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from '../components/App.Header';
import { Container } from 'react-bootstrap';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
      <Container>
       {children}
      </Container>
      </body>
    </html>
  )
}
